services:
  frontend:
    container_name: Vite-React-Page-dev
    image: vite-react-app:v1.0.0-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5173:5173
