apiVersion: apps/v1
kind: Deployment
metadata:
  name: vite-deployment
  namespace: dev
  labels:
    app: vite-react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vite-react-app
  template:
    metadata:
      labels:
        app: vite-react-app
    spec:
      containers:
        - name: vite-react-app
          image: panchanandevops/vite-react-app:2.4.8
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
            requests:
              memory: "64Mi"
              cpu: "100m"
