name: Build and Push Vite React Docker Image

permissions:
  security-events: write
  contents: write  # Required for creating branches and pull requests

on:
  push:
    tags:
      - "v*.*.*" # Trigger on pushes of tags matching v1.0.0, v2.1.3, etc.
    paths-ignore:
      - "README.md" # Ignore changes to README.md

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Docker metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: panchanandevops/vite-react-app
          flavor: |
            latest=false
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push Vite React Docker image
        uses: docker/build-push-action@v6
        with:
          context: . # Set the context to the root directory
          file: Dockerfile # Set the Dockerfile path to Dockerfile in the root directory
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      

      - name: Run Trivy for HIGH, CRITICAL CVEs and report
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ steps.meta.outputs.tags }}"
          exit-code: 0 # Do not fail the workflow on vulnerabilities
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "HIGH,CRITICAL"
          format: "sarif"
          output: "trivy-results.sarif"
  
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: "trivy-results.sarif"
            
            
      - name: Create a new branch
        run: |
          git checkout -b update-deployment-image-${{ github.sha }}

      - name: Update deployment image in Kubernetes YAML
        run: |
          sed -i "s|image: .*/vite-react-app:.*|image: ${{ steps.meta.outputs.tags }}|" Deploy/k8s/1-deployment-vite.yaml
          git add Deploy/k8s/1-deployment-vite.yaml
          git commit -m "Update deployment image to ${{ steps.meta.outputs.tags }}"

      - name: Push the new branch
        run: |
          git push origin update-deployment-image-${{ github.sha }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: update-deployment-image-${{ github.sha }}
          title: "Update deployment image to ${{ steps.meta.outputs.tags }}"
          body: "This PR updates the deployment image in 1-deployment-vite.yaml to use the newly built image."
          labels: |
            automated-pr
          reviewers: panchanandevops