name: Build and Push vite reacts Docker Image

on:
  push:
    branches:
      - main     # Trigger on pushes to the main branch
    tags:
      - 'v*.*.*' # Trigger on pushes of tags matching v1.0.0, v2.1.3, etc.
    paths-ignore:
      - 'README.md' # Ignore changes to README.md

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Docker metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: panchanandevops/vite-react-app
          tags: |
            type=semver,pattern={{version}}
            type=sha

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: .          # Set the context to the root directory
          file: Dockerfile   # Set the Dockerfile path to Dockerfile in the root directory
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}